import { CheckCircle2, Compass, HeartHandshake, Lightbulb, Target } from "lucide-react";
import PublicShell from "@/components/PublicShell";
import { normalizeMediaUrl, usePublicSite } from "@/lib/site";

export default function About() {
  const { data, isLoading } = usePublicSite(); if (isLoading) return <div className="min-h-screen bg-[#fbfcfa]" />;
  const settings = data?.settings; const section = data?.sections?.find((item: any) => item.sectionKey === "about_values"); const values = (settings?.values || "السهولة، الوضوح، تنوع الخدمات، والتواصل المباشر.").split("،");
  return <PublicShell data={data}><section className="page-hero"><div className="container grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="section-kicker">من نحن</p><h1 className="mt-3 text-4xl font-black leading-tight tracking-[-.035em] text-[#103d3b] sm:text-5xl">{settings?.aboutTitle || "منصة تُسهّل احتياجاتك اليومية"}</h1><p className="mt-5 max-w-2xl leading-8 text-[#5d716c]">{settings?.aboutDescription || "ضياء موبايل منصة للخدمات الرقمية والاتصالات."}</p></div><div className="mx-auto max-w-sm overflow-hidden rounded-[2rem] border border-white bg-white p-3 shadow-xl"><img src={normalizeMediaUrl(settings?.logoUrl, "/media/diaa-app-icon.jpg")} alt="شعار ضياء موبايل" className="aspect-square w-full rounded-[1.45rem] object-cover" /></div></div></section><section className="container py-16 lg:py-24"><div className="grid gap-5 md:grid-cols-3"><article className="rounded-[1.6rem] bg-[#0b4d4a] p-7 text-white"><Target className="h-7 w-7 text-[#e5c382]" /><h2 className="mt-7 text-2xl font-black">رسالتنا</h2><p className="mt-3 leading-7 text-[#d0e2da]">{settings?.mission || "أن نجعل الوصول إلى الخدمات الرقمية اليومية تجربة واضحة وعملية."}</p></article><article className="rounded-[1.6rem] border border-[#e0ebe5] bg-white p-7"><Compass className="h-7 w-7 text-[#0b4d4a]" /><h2 className="mt-7 text-2xl font-black text-[#103d3b]">رؤيتنا</h2><p className="mt-3 leading-7 text-[#6c807a]">منصة رقمية موثوقة وسهلة الوصول تساعد المستخدم على إدارة احتياجاته اليومية من مكان واحد.</p></article><article className="rounded-[1.6rem] border border-[#e0ebe5] bg-[#f3f8f5] p-7"><HeartHandshake className="h-7 w-7 text-[#c19249]" /><h2 className="mt-7 text-2xl font-black text-[#103d3b]">وعدنا</h2><p className="mt-3 leading-7 text-[#6c807a]">لغة واضحة، مسارات استخدام أبسط، وقنوات تواصل مباشرة تساعدك عند الحاجة.</p></article></div></section><section className="bg-[#f3f8f5]"><div className="container grid gap-10 py-16 lg:grid-cols-[.8fr_1.2fr] lg:py-20"><div><p className="section-kicker">{section?.label || "قيمنا"}</p><h2 className="mt-3 text-3xl font-black leading-tight text-[#103d3b]">{section?.title || "سهولة الوصول إلى الخدمات الرقمية"}</h2><p className="mt-5 leading-8 text-[#647872]">{section?.body || "نضع الوضوح وسهولة الاستخدام في مقدمة تجربة ضياء موبايل."}</p></div><div className="grid gap-3 sm:grid-cols-2">{values.map((value: string, index: number) => <div key={value} className="flex items-center gap-3 rounded-2xl border border-[#dae8e1] bg-white p-4"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#e8f2ed] text-xs font-black text-[#0b4d4a]">0{index + 1}</span><span className="font-bold text-[#1b4a47]">{value.trim()}</span></div>)}</div></div></section></PublicShell>;
}
