import { ArrowUpLeft, Facebook, Instagram, Mail, MapPin, Phone, Send, Smartphone } from "lucide-react";
import PublicShell from "@/components/PublicShell";
import { usePublicSite } from "@/lib/site";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = { Facebook, Instagram, Music2: Send, Play: Smartphone };

export default function Contact() {
  const { data, isLoading } = usePublicSite(); if (isLoading) return <div className="min-h-screen bg-[#fbfcfa]" />;
  const settings = data?.settings; const section = data?.sections?.find((item: any) => item.sectionKey === "contact_support"); const socials = (data?.links || []).filter((item: any) => item.linkType === "social");
  return <PublicShell data={data}><section className="page-hero"><div className="container"><p className="section-kicker">{section?.label || "الدعم والتواصل"}</p><h1 className="mt-3 max-w-3xl text-4xl font-black leading-tight tracking-[-.035em] text-[#103d3b] sm:text-5xl">{section?.title || "نحن هنا لمساعدتك"}</h1><p className="mt-5 max-w-2xl leading-8 text-[#5d716c]">{section?.body || "تواصل مع فريق ضياء موبايل عبر القنوات الرسمية."}</p></div></section><section className="container py-14 lg:py-20"><div className="grid gap-4 md:grid-cols-2"><a href={`tel:${(settings?.phone || "+967 780 777 735").replace(/\s/g, "")}`} className="group rounded-[1.5rem] border border-[#deebe5] bg-white p-7 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e9f3ee] text-[#0b4d4a]"><Phone className="h-5 w-5" /></div><p className="mt-6 text-sm font-bold text-[#758883]">اتصل بنا</p><p className="mt-1 text-xl font-black text-[#103d3b]" dir="ltr">{settings?.phone || "+967 780 777 735"}</p><span className="mt-5 inline-flex items-center gap-1.5 text-sm font-extrabold text-[#0b4d4a]">اتصال مباشر <ArrowUpLeft className="h-4 w-4" /></span></a><a href={`mailto:${settings?.email || "diaamobile01@gmail.com"}`} className="group rounded-[1.5rem] border border-[#deebe5] bg-white p-7 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#f7f0e5] text-[#a86c1c]"><Mail className="h-5 w-5" /></div><p className="mt-6 text-sm font-bold text-[#758883]">البريد الإلكتروني</p><p className="mt-1 text-xl font-black text-[#103d3b]">{settings?.email || "diaamobile01@gmail.com"}</p><span className="mt-5 inline-flex items-center gap-1.5 text-sm font-extrabold text-[#0b4d4a]">إرسال رسالة <ArrowUpLeft className="h-4 w-4" /></span></a></div><div className="mt-8 rounded-[1.7rem] bg-[#0b4d4a] p-7 text-white sm:p-9"><div className="flex items-start gap-4"><MapPin className="mt-1 h-5 w-5 text-[#e4c17f]" /><div><p className="text-sm font-extrabold text-[#e5c382]">منصاتنا الرسمية</p><h2 className="mt-2 text-2xl font-black">تابع ضياء موبايل وتواصل معنا</h2><p className="mt-2 max-w-xl text-sm leading-7 text-[#c9ddd5]">اختر الحساب الرسمي الذي يناسبك لمتابعة المستجدات أو الوصول إلى رابط التطبيق.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{socials.map((social: any) => { const Icon = iconMap[social.icon] || Send; return <a key={social.id} href={social.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 py-3.5 font-bold transition hover:bg-white/10"><span className="inline-flex items-center gap-2"><Icon className="h-4 w-4 text-[#e4c17f]" />{social.label}</span><ArrowUpLeft className="h-4 w-4" /></a>})}</div></div></section></PublicShell>;
}
