import { Link } from "wouter";
import { ArrowLeft, ArrowLeftRight, Download, Gamepad2, ReceiptText, Smartphone, Trophy, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import PublicShell from "@/components/PublicShell";
import { categoryLabels, findLink, usePublicSite } from "@/lib/site";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = { Smartphone, Wifi, ReceiptText, ArrowLeftRight, Gamepad2, Trophy };
const categories = ["telecom", "payments", "games"] as const;

export default function Services() {
  const { data, isLoading } = usePublicSite(); if (isLoading) return <div className="min-h-screen bg-[#fbfcfa]" />;
  const section = data?.sections?.find((item: any) => item.sectionKey === "services_intro"); const appUrl = findLink(data, "google_play", "https://play.google.com/store/apps/details?id=diaamobile.likhadmatsadad");
  return <PublicShell data={data}><section className="page-hero"><div className="container relative"><p className="section-kicker">{section?.label || "الخدمات"}</p><h1 className="mt-3 max-w-3xl text-4xl font-black leading-tight tracking-[-.035em] text-[#103d3b] sm:text-5xl">{section?.title || "خدمات مصممة لاحتياجاتك اليومية"}</h1><p className="mt-5 max-w-2xl leading-8 text-[#5d716c]">{section?.body || "تعرّف على خدمات ضياء موبايل."}</p></div></section><section className="container py-14 lg:py-20"><div className="space-y-12">{categories.map((category, categoryIndex) => { const items = (data?.services || []).filter((item: any) => item.category === category); const shades = ["#e9f3ee", "#f6f0e5", "#e8f0f7"]; return <div key={category}><div className="mb-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0b4d4a] text-sm font-black text-white">0{categoryIndex + 1}</span><h2 className="text-2xl font-black text-[#103d3b]">{categoryLabels[category]}</h2></div><div className="grid gap-4 md:grid-cols-2">{items.map((item: any) => { const Icon = iconMap[item.icon] || Smartphone; return <article key={item.id} className="rounded-[1.5rem] border border-[#dfe9e4] bg-white p-6 transition hover:shadow-lg"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl" style={{ backgroundColor: shades[categoryIndex] }}><Icon className="h-5 w-5 text-[#0b4d4a]" /></div><div><h3 className="text-lg font-extrabold text-[#123d3a]">{item.title}</h3><p className="mt-2 text-sm leading-7 text-[#667b75]">{item.description}</p></div></div></article>})}</div></div>})}</div></section><section className="border-y border-[#deebe5] bg-[#f3f8f5]"><div className="container py-14"><p className="section-kicker">شركات الاتصالات</p><h2 className="mt-3 text-3xl font-black text-[#103d3b]">الشركات المدعومة</h2><div className="mt-7 grid gap-4 sm:grid-cols-3">{(data?.companies || []).map((company: any) => <div key={company.id} className="rounded-2xl border border-[#dbe8e1] bg-white p-5"><div className="mb-4 h-2 w-12 rounded-full bg-[#d7af69]" /><h3 className="font-extrabold text-[#123d3a]">{company.name}</h3><p className="mt-2 text-sm leading-6 text-[#71847e]">{company.description}</p></div>)}</div></div></section><section className="container py-16"><div className="flex flex-col items-start justify-between gap-5 rounded-[2rem] bg-[#0b4d4a] p-8 text-white sm:p-11 md:flex-row md:items-center"><div><h2 className="text-2xl font-black">الخدمة التي تحتاجها أقرب مما تتوقع.</h2><p className="mt-2 text-sm leading-7 text-[#cbe0d7]">حمّل التطبيق واستكشف الخدمات والخيارات المتاحة فيه.</p></div><a href={appUrl} target="_blank" rel="noreferrer"><Button className="h-12 gap-2 rounded-xl bg-white px-5 font-extrabold text-[#0b4d4a] hover:bg-[#f4f7f5]"><Download className="h-4 w-4" />تحميل التطبيق</Button></a></div></section></PublicShell>;
}
